### PR TITLE
more stuff

### PR DESCRIPTION
**Pull request by bodepd**

### CODE REVIEW

**Comment by bodepd** [comment]
schedule_for_testing

**Comment by puppet-openstack-ci-user** [comment]
Test SUCCESS. Results can be found here: https://gist.github.com/5129964

**Comment by puppet-openstack-ci-user** [comment]
Test SUCCESS. Results can be found here: https://gist.github.com/5129965

**Comment by puppet-openstack-ci-user** [comment]
Test SUCCESS. Results can be found here: https://gist.github.com/5130032

**Comment by puppet-openstack-ci-user** [comment]
Test SUCCESS. Results can be found here: https://gist.github.com/5130031

**Comment by puppet-openstack-ci-user** [comment]
Test SUCCESS. Results can be found here: https://gist.github.com/5130045

**Comment by puppet-openstack-ci-user** [comment]
Test SUCCESS. Results can be found here: https://gist.github.com/5130046

**Pull request closed without merging**
